USE [master]
GO

CREATE DATABASE [HawkSoftDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HawkSoftDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HawkSoftDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HawkSoftDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HawkSoftDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HawkSoftDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HawkSoftDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HawkSoftDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HawkSoftDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HawkSoftDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HawkSoftDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [HawkSoftDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HawkSoftDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HawkSoftDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HawkSoftDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HawkSoftDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HawkSoftDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HawkSoftDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HawkSoftDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HawkSoftDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HawkSoftDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HawkSoftDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HawkSoftDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HawkSoftDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HawkSoftDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HawkSoftDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HawkSoftDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HawkSoftDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HawkSoftDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HawkSoftDb] SET  MULTI_USER 
GO

ALTER DATABASE [HawkSoftDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HawkSoftDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HawkSoftDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HawkSoftDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HawkSoftDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HawkSoftDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HawkSoftDb] SET  READ_WRITE 
GO




USE [HawkSoftDb]
GO

/****** Object:  Table [dbo].[User]    Script Date: 8/8/2021 10:10:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Contact](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Address] [varchar](100) NOT NULL,
	[City] [varchar](50) NOT NULL,
	[State] [varchar](50) NOT NULL,
	[Zipcode] [varchar](50) NOT NULL,
	[UserId] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Contact] ADD  CONSTRAINT [DF_Contact_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO

ALTER TABLE [dbo].[Contact] CHECK CONSTRAINT [FK_Contact_User]
GO

INSERT INTO [dbo].[User] (Name) VALUES ('User1')
GO

INSERT INTO [dbo].[User] (Name) VALUES ('User2')
GO

INSERT INTO [dbo].[User] (Name) VALUES ('User3')
GO